---
CSR1000V_LatestCode:
  hostname: 'sandbox-iosxe-latest-1.cisco.com'
  port: 22
  username: 'developer'
  password: 'C1sco12345'
  platform: 'cisco_xe'
  groups:
    - 'cisco_ios'
CSR1000V_Recommended:
  hostname: 'ios-xe-mgmt.cisco.com'
  port: 8181
  username: 'developer'
  password: 'C1sco12345'
  platform: 'cisco_xe'
  groups:
    - 'cisco_ios'
